/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisualizarRouteImport } from './routes/visualizar'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CodificarRouteImport } from './routes/codificar'
import { Route as IndexRouteImport } from './routes/index'

const VisualizarRoute = VisualizarRouteImport.update({
  id: '/visualizar',
  path: '/visualizar',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CodificarRoute = CodificarRouteImport.update({
  id: '/codificar',
  path: '/codificar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/codificar': typeof CodificarRoute
  '/login': typeof LoginRoute
  '/painel': typeof PainelRoute
  '/visualizar': typeof VisualizarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/codificar': typeof CodificarRoute
  '/login': typeof LoginRoute
  '/painel': typeof PainelRoute
  '/visualizar': typeof VisualizarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/codificar': typeof CodificarRoute
  '/login': typeof LoginRoute
  '/painel': typeof PainelRoute
  '/visualizar': typeof VisualizarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/codificar' | '/login' | '/painel' | '/visualizar'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/codificar' | '/login' | '/painel' | '/visualizar'
  id: '__root__' | '/' | '/codificar' | '/login' | '/painel' | '/visualizar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CodificarRoute: typeof CodificarRoute
  LoginRoute: typeof LoginRoute
  PainelRoute: typeof PainelRoute
  VisualizarRoute: typeof VisualizarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visualizar': {
      id: '/visualizar'
      path: '/visualizar'
      fullPath: '/visualizar'
      preLoaderRoute: typeof VisualizarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codificar': {
      id: '/codificar'
      path: '/codificar'
      fullPath: '/codificar'
      preLoaderRoute: typeof CodificarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CodificarRoute: CodificarRoute,
  LoginRoute: LoginRoute,
  PainelRoute: PainelRoute,
  VisualizarRoute: VisualizarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
